services:
  postgres:
    image: postgres:latest    # Added version tag
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres    # Consider using a more secure password
      POSTGRES_DB: postgres
    ports:
      - "5632:5432"    # Added quotes for consistency
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:    # Added healthcheck
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog:latest    # Added version tag
    restart: on-failure
    ports:
      - "1125:1025"
      - "8025:8025"
    volumes:
      - mailhog:/data
    logging:    # Added logging configuration
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  data:
  mailhog:
